/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.1-1-geb64e040ab-g6c4074e423+332"
#endif /* AVUTIL_FFVERSION_H */
