SET(CMAKE_RC_COMPILER_INIT windres)

LIST(APPEND CMAKE_PROGRAM_PATH D:/mas/local64/bin)
SET(CMAKE_FIND_ROOT_PATH D:/mas/local64;D:/mas/msys64/mingw64;D:/mas/msys64/mingw64/x86_64-w64-mingw32)
SET(CMAKE_PREFIX_PATH D:/mas/local64;D:/mas/msys64/mingw64;D:/mas/msys64/mingw64/x86_64-w64-mingw32)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_BUILD_TYPE Release)
